### PR TITLE
Fixed all apis + added integration tests

### PR DESCRIPTION
**Pull request by miparnisari**
This package seems completely broken. For starters, the existing `verifyParameters -> makeRequest` code does not work, it is missing a `return` statement. Also, the various APIs now support different endpoints that need to be specified.

With this CR, the clients updated now require an extra parameter `endpoint`. For example:

```javascript
    const client = cognitive.computerVision({
        apiKey: "your-key",
        endpoint: "westus.api.cognitive.microsoft.com"
    });
```

Also, when making the calls, a `headers` parameter is now required:

```javascript
	const parameters = {
		returnFaceId: "true",
		returnFaceLandmarks: "true",
		returnFaceAttributes: "age,gender,headPose,smile,facialHair,glasses"
	};
	const headers = {
		'Content-type': 'application/json'
	};
	const body = {
		"url": "http://techstory.in/wp-content/uploads/2015/02/sachin-tendulkar-sifr-651867782.jpg"
	};

	face.detect({
		parameters,
		headers,
		body
	})
```

I added some tests, ideally each specific API would have at least one test.

To run the integration tests:
1. Run `npm install`
1. Add your own api keys in `test/config.js` 
1. Run `gulp test`

TO DO 
- [x] academic knowledge
- [x] bing auto suggest
- [x] bing image search
- [x] bing news search
- [x] bing spell check
- [x] bing video search
- [x] bing web search
- [x] computer vision
- [x] emotion
- [x] entity linking
- [x] face
- [x] recommendations
- [x] speaker recognition
- [x] text analytics
- [x] video
- [x] web language model

### CODE REVIEW

**Comment by joshbalfour** [comment]
Hi @miparnisari, thank you so much for your contribution!!
Because this is so big I've invited you to be a contributor to the repo, feel free to merge as you go.
Let me know when you want me to publish to npm, I'll look to add travis to the repo too so it gets auto published.
Your work is very much appreciated, thanks again!

**Comment by miparnisari** [comment]
Hey @joshbalfour, no problem, thanks for making me a contributor :)

It's going to take some time before I get all the apis updated. I need to double check the documentation to make sure that the parameters are up to date, check that there aren't any new/deprecated APIs, etc.

**Comment by miparnisari** [comment]
I also intended to add coverage support but i can't seem to get `gulp-coverage` to work :( it always returns 0% covered

**Comment by miparnisari** [comment]
@joshbalfour can you publish to npm?

**Pull request merged**
